### ISSUE TITLE
eglot: didChangeConfiguration parameters might be empty

### ISSUE THREAD

**Issue by pedro-w** [dylan-lang/lsp-dylan#20]
VSCode always sent a json object with at least a 'dylan' key when issuing the didChangeConfiguration notification but [the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didChangeConfigurationParams) does not require that. eglot doesn't and this causes the server to crash.

**Comment by cgay** [comment]
I think this may have been fixed by https://github.com/dylan-lang/lsp-dylan/pull/22/commits/7a7b0faa78496ab495301d23852487cc342a8a1e but I haven't tested in VS Code.

**Comment by pedro-w** [comment]
Great, I will test asap

**Comment by pedro-w** [comment]
Works fine on VS code AFAICS
